# Generated by Django 4.0.3 on 2022-06-15 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BapProje', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='basvurukapak',
            old_name='proje_suresi',
            new_name='proje_suresi_Ay_cinsinden',
        ),
        migrations.AlterField(
            model_name='basvurukapak',
            name='proje_sahibi_cv',
            field=models.FileField(blank=True, upload_to=''),
        ),
    ]
