# Generated by Django 4.0.3 on 2022-06-17 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BapProje', '0002_rename_proje_suresi_basvurukapak_proje_suresi_ay_cinsinden_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjePersoneli',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gorev', models.CharField(max_length=255)),
                ('unvan', models.CharField(max_length=255)),
                ('adi', models.CharField(max_length=50)),
                ('soyadi', models.CharField(max_length=55)),
                ('tc_no', models.CharField(max_length=11)),
                ('universite', models.CharField(max_length=255)),
                ('fakulte', models.CharField(max_length=255)),
                ('bolum', models.CharField(max_length=255)),
                ('e_posta', models.EmailField(max_length=254)),
                ('cv', models.FileField(blank=True, upload_to='')),
            ],
        ),
    ]
