# Generated by Django 4.0.3 on 2022-06-17 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BapProje', '0003_projepersoneli'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projepersoneli',
            name='gorev',
            field=models.CharField(choices=[('Araştırmacı', 'Ars'), ('Danışman', 'Dns'), ('Bursiyer', 'Brs')], max_length=255),
        ),
        migrations.AlterField(
            model_name='projepersoneli',
            name='unvan',
            field=models.CharField(choices=[('Prof. Dr.', 'Prof. Dr.'), ('Doç. Dr.', 'Doç. Dr.'), ('Yrd. Doç. Dr.', 'Yrd. Doç. Dr.'), ('Dr. Öğr. Üyesi', 'Dr. Öğr. Üyesi'), ('Uzm. Dr.', 'Uzm. Dr.'), ('Dr.', 'Dr.'), ('Uzm.', 'Uzm.'), ('Arş. Gör.', 'Arş. Gör.'), ('Arş. Gör. Dr.', 'Arş. Gör. Dr.'), ('Öğr. Gör. Dr.', 'Öğr. Gör. Dr.'), ('Öğr. Gör.', 'Öğr. Gör.'), ('Öğrenci', 'Öğrenci'), ('Yüksek Lisans Öğrencisi', 'Yüksek Lisans Öğrencisi'), ('Doktora Öğrencisi', 'Doktora Öğrencisi'), ('Diğer', 'Diğer')], max_length=255),
        ),
    ]
