# Generated by Django 4.0.3 on 2022-06-17 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BapProje', '0005_alter_projepersoneli_gorev'),
    ]

    operations = [
        migrations.CreateModel(
            name='BelgeYukle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Dosya', models.FileField(blank=True, upload_to='')),
            ],
        ),
    ]
