# Generated by Django 4.0.3 on 2022-06-17 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BapProje', '0007_projehakemi'),
    ]

    operations = [
        migrations.AddField(
            model_name='projehakemi',
            name='resim',
            field=models.ImageField(blank=True, upload_to='images/'),
        ),
    ]
