# Generated by Django 4.0.3 on 2022-06-18 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BapProje', '0008_projehakemi_resim'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjeEkDosya',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Dosya_Basligi', models.CharField(max_length=100)),
                ('Aciklamasi', models.CharField(max_length=200)),
                ('Dosya', models.FileField(upload_to='')),
            ],
        ),
    ]
