# Generated by Django 4.0.3 on 2022-06-28 15:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BapProje', '0011_projealimlari'),
    ]

    operations = [
        migrations.RenameField(
            model_name='projealimlari',
            old_name='basvuran',
            new_name='basvuran_id',
        ),
    ]
