# Generated by Django 4.0.3 on 2022-06-28 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BapProje', '0012_rename_basvuran_projealimlari_basvuran_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projepersoneli',
            name='cv',
            field=models.FileField(blank=True, upload_to='docs/'),
        ),
    ]
