# Generated by Django 4.0.3 on 2022-06-29 20:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BapProje', '0013_alter_projepersoneli_cv'),
    ]

    operations = [
        migrations.RenameField(
            model_name='projeekdosya',
            old_name='basvuran',
            new_name='basvuran_id',
        ),
    ]
