# Generated by Django 4.0.3 on 2022-06-29 20:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BapProje', '0014_rename_basvuran_projeekdosya_basvuran_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projeekdosya',
            name='basvuran_id',
        ),
    ]
