# Generated by Django 4.0.3 on 2022-06-29 20:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('BapProje', '0015_remove_projeekdosya_basvuran_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='belgeyukle',
            name='basvuran',
        ),
        migrations.AddField(
            model_name='belgeyukle',
            name='basvuran_id',
            field=models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
